language: objective-c
os: osx
osx_image: xcode8

cache: cocoapods
podfile: Example/Podfile
before_install:
  - gem install xcpretty -N --no-ri --no-rdoc
  - gem install cocoapods --pre
  - pod install --project-directory=Example
script:
  - set -o pipefail && xcodebuild clean test -workspace Example/EFCountingLabel.xcworkspace -scheme EFCountingLabel-Example -destination "platform=iOS Simulator,name=iPhone 6 Plus" | xcpretty
  - pod lib lint --no-clean
after_success:
  - sleep 5